added note about shorter command 'docker build'
docker/cli pull request #1703
Opened 2019-03-01 15:11 UTC by thadguidry

**- What I did**
Documentation Improvement

**- How I did it**
This will help clarify to users that they are the same command.
As well as make it clear in the auto-generated docs https://docs.docker.com/engine/reference/commandline/image_build/

**- How to verify it**

**- Description for the changelog**
Added note to 'docker image build' about shorter syntax 'docker build'

2019-03-01 15:11 UTC, GordonTheTurtle commented
<!-- AUTOMATED:POULE:DCO-EXPLANATION -->
Please sign your commits following these rules:
https://github.com/moby/moby/blob/master/CONTRIBUTING.md#sign-your-work
The easiest way to do this is to amend the last commit:
~~~console
$ git clone -b "patch-1" git@github.com:thadguidry/cli.git somewhere
$ cd somewhere
$ git commit --amend -s --no-edit
$ git push -f
~~~

Amending updates the existing PR. You **DO NOT** need to open a new one.

2019-03-21 21:45 UTC, tiborvass commented
Thank you for your contribution but this is not specific to build, so we'd need to either make it consistent across all aliased commands or decide not to take it, sorry!

2019-03-22 01:20 UTC, thadguidry commented
That's unfortunate because it was a question asked by 3 independent Ericsson developers towards our Devops group and I had to explain this to them and puzzled why they didn't know...they said... "their docs really didn't explain that well, thanks for explaining to us Thad."

2019-03-22 05:23 UTC, tiborvass commented
@thadguidry I'm not against clarifying that if that's confusing. I just think other commands need the same adjustments "docker container run` == `docker run` etc. Also, you are modifying the help output within the documentation, but not the help output in the code itself. If you need help let us know.

2020-11-23 11:45 UTC, adeniyistephen commented
@tiborvass @thaJeztah As the documentation be updated yet? Can i work on this i would love to kindly provide input or pointers.

2023-12-21 00:16 UTC, thaJeztah requested changes

2023-12-21 00:16 UTC, thaJeztah commented on docs/reference/commandline/image.md
> +  build       Build an image from a Dockerfile (same as 'docker build')
This example shows the output how the CLI itself prints it, which does not include this).


We added additional metadata, and usage output in these PR's though (and will be using those in the documentation);

- https://github.com/docker/cli/pull/3693
- https://github.com/docker/cli/pull/3694

2023-12-21 00:16 UTC, thaJeztah commented
closing this per above, but thanks for contributing!

2023-12-21 00:16 UTC, closed without merging