Update kill.md
docker/cli pull request #2816
Opened 2020-10-26 23:49 UTC by callmePicacho

only SIGKILL，not KILL signal

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

2020-11-06 09:08 UTC, silvin-lubecki requested changes
Hello @callmePicacho and thanks for this PR, but I think this help message is accurate.
It's the same output as `docker kill --help`. By the way both `KILL` and `SIGKILL` are accepted, it's just that the default one is `KILL` when you don't specify the flag.

2020-11-06 14:40 UTC, devdreamsolution approved these changes

2020-11-13 09:02 UTC, thaJeztah requested changes
I agree. I understand it may be somewhat confusing (because `SIGKILL` (`SIGxxx`) and `KILL` are used interchangeably, but the current docs reflect the actual value that's set as default, and reflects what the cli `--help` output prints;


```console
$ docker kill --help | grep signal
  -s, --signal string   Signal to send to the container (default "KILL")
```

2020-11-13 09:03 UTC, thaJeztah commented
Let me close this PR, per the above discussion.

Thank you for contributing! Even though we didn't merge your PR, it _is_ appreciated!

2020-11-13 09:03 UTC, closed without merging