Modify a 'docker build' command with no context specified to infer a …
docker/cli pull request #2947
Opened 2021-01-23 20:08 UTC by marzhall

…context of '.'. Also update documentation to match.

Signed-off-by: Marshall Conover <marzhall.o+docker@gmail.com>

*- What I did**
Removed the requirement to specify a context when running docker build.
**- How I did it**
Modified the options parsing for `docker build` to use the current working directory as the context when no context is specified.
**- How to verify it**
In a directory with a Dockerfile, and with an updated binary, run:
```
    docker build
```
You will see the docker build command execute as if you had run `docker build .`.

This is in contrast to the previous behavior, in which case running `docker build` would return:
```
    "docker build" requires exactly 1 argument.
```
followed by the client exiting.

**- Description for the changelog**

PR for #2946 

**- A picture of a cute animal (not mandatory but encouraged)**
![image](https://user-images.githubusercontent.com/973107/105611184-bf810480-5d81-11eb-85a0-71ac62687abf.png)

2021-01-25 12:19 UTC, thaJeztah requested changes
Thanks for contributing! This change will need further discussion. We've had a look at similar changes in the past, and there's some reasons for not making this change;

- keeping it explicit makes sure that unintended missing paths produce an error, instead of "silently" picking the current directory. These situations happen, e.g., when using an environment variable to specify the path (`docker build $SOME_VARIABLE`)
- we want to keep the option open to use `docker build` (without specifying options or a path) to perform a more "interactive" build. No decisions were made on this yet, but changing the behavior to default to `.` would no longer allow us to move in that direction without introducing a breaking change.

For reasons above, I'm "-1" on merging this; I do understand where you're coming from though 🤗

2021-01-25 14:23 UTC, marzhall commented
Hi thaJeztah!

I don't know if that's considered the final word or not, but in case not, I'll just throw in a few thoughts:

- For the first point, that's totally reasonable; would a line to stdout or stderr saying "no context was specified, so we're defaulting to the current directory" address that? I can add that later today.
- For the second point, while the idea is interesting, I'm not sure sacrificing a clear and easy-to-implement feature that improves QoL immediately for a feature that might potentially be implemented in the future is the best priority planning-wise. In the case interactive mode was desired after this change went in, it could be implemented as a switch (e.g. `--interactive`), which I think would also better match its frequency of use by developers; intuitively, I think developers who forget to specify a context are more likely to intend to have typed `.` than to want a manual prompt. In my example of making the mistake in my builds, for example, it would've been only slightly less frustrating. Having a prompt appear when no context is specified also makes the client continue to have 'surprising' behavior vs. its other command-line cousins like `ls` who require directories be specified, and infer you meant the local directory should you not specify one.

Let me know if it would be more convenient to discuss this in another spot, and thanks for your time!

2021-01-25 23:02 UTC, marzhall commented
I've added informational output to inform the user when the context has been inferred, e.g.:

```
$ build/docker-linux-amd64 build
No build context was specified. Using the current working directory '/home/mars/fun/cli' as our build context.
Sending build context to Docker daemon  45.37MB
Step 1/2 : FROM ubuntu
 ---> f63181f19b2f
Step 2/2 : RUN echo test
 ---> Using cache
 ---> c8e2247d0739
Successfully built c8e2247d0739
```

2026-05-14 22:07 UTC, thaJeztah commented
closing for now, as this is no longer in a mergeable state

2026-05-14 22:07 UTC, closed without merging