Document option for daemon config validation
docker/cli pull request #3108
Opened 2021-05-25 14:43 UTC by aiordache

We are adding a `--validate` option to dockerd to check if the config file is valid without starting the daemon.

Related to https://github.com/moby/moby/pull/42393

**- What I did**
Added `--validate` option to the docker daemon options documentation.

**- Description for the changelog**
Update documentation and shell completion for the daemon validation option.

2021-05-25 15:21 UTC, thaJeztah commented on docs/reference/commandline/dockerd.md
> +```console
nit: can you add a blank line before the code block?

2021-05-25 15:22 UTC, thaJeztah commented
I moved this temporarily to "draft", pending https://github.com/moby/moby/pull/42393 to be merged

2021-05-27 08:54 UTC, albers approved these changes
completion LGTM, thanks

2021-05-27 09:22 UTC, thaJeztah approved these changes
LGTM

2021-06-23 18:24 UTC, thaJeztah commented
moved out of draft as moby PR was merged, but it needs a minor update (I'll leave a comment)

2021-06-23 18:24 UTC, thaJeztah commented
moved out of draft as moby PR was merged, but it needs a minor update (I'll leave a comment)

2021-06-23 18:27 UTC, thaJeztah requested changes
left a comment 🤗

2021-06-23 18:27 UTC, thaJeztah commented on docs/reference/commandline/dockerd.md
> +Config OK
This changed to 

```suggestion
configuration OK
```

2021-06-23 18:27 UTC, thaJeztah commented on docs/reference/commandline/dockerd.md
> +Config OK
Should we also mention that the exit status will be 0 (success) and non-zero (failure)? as that's the "actual" check (message that's printed is informational)?

2021-06-24 14:22 UTC, thaJeztah approved these changes
LGTM, thanks!

2021-06-24 14:25 UTC, merged