Drop support for (archived) Compose-on-Kubernetes
docker/cli pull request #3139
Opened 2021-06-16 07:13 UTC by ndeloof

closes https://github.com/docker/cli/issues/2967
(https://docker.atlassian.net/browse/IL-257 for internal tracker)

**- What I did**
Removed support for Kubernetes orchestrator, as required [compose-on-kubernetes](https://github.com/docker/compose-on-kubernetes) backend is archived

**- How I did it**
Code removal

**- How to verify it**
isn't this what CI is for ? :P

**- Description for the changelog**
Removed support for deprecated Compose-on-Kubernetes

**- A picture of a cute animal (not mandatory but encouraged)**
![image](https://user-images.githubusercontent.com/132757/122174389-fa93e980-ce82-11eb-8f22-df56fe79ba1f.png)

2021-06-21 09:42 UTC, thaJeztah commented
Does this mean we should also remove the "kubernetes endpoint" from `docker context` ?

2021-06-21 10:03 UTC, ndeloof commented
@thaJeztah yes indeed

2021-08-03 10:30 UTC, eclipseo commented
There are still instances of compose-on-kubernetes in the source even with this patch:

```
kubernetes/check.go
4:      apiv1alpha3 "github.com/docker/compose-on-kubernetes/api/compose/v1alpha3"
5:      apiv1beta1 "github.com/docker/compose-on-kubernetes/api/compose/v1beta1"
6:      apiv1beta2 "github.com/docker/compose-on-kubernetes/api/compose/v1beta2"

kubernetes/labels/labels.go
3:import labels "github.com/docker/compose-on-kubernetes/api/labels"
7:      // Deprecated: Use github.com/docker/compose-on-kubernetes/api/labels.ForServiceName instead
10:     // Deprecated: Use github.com/docker/compose-on-kubernetes/api/labels.ForStackName instead
13:     // Deprecated: Use github.com/docker/compose-on-kubernetes/api/labels.ForServiceID instead
18:// Deprecated: Use github.com/docker/compose-on-kubernetes/api/labels.ForService instead
23:// Deprecated: Use github.com/docker/compose-on-kubernetes/api/labels.SelectorForStack instead

kubernetes/compose/impersonation/impersonationconfig.go
3:import api "github.com/docker/compose-on-kubernetes/api/compose/impersonation"
6:// Deprecated: Use github.com/docker/compose-on-kubernetes/api/compose/impersonation.Config instead

kubernetes/compose/v1beta1/owner.go
3:import api "github.com/docker/compose-on-kubernetes/api/compose/v1beta1"
7:// Deprecated: Use github.com/docker/compose-on-kubernetes/api/compose/v1beta1.Owner instead

kubernetes/client/listers/compose/v1beta2/stack.go
3:import api "github.com/docker/compose-on-kubernetes/api/client/listers/compose/v1beta2"
6:// Deprecated: Use github.com/docker/compose-on-kubernetes/api/client/listers/compose/v1beta2.StackLister instead
10:// Deprecated: Use github.com/docker/compose-on-kubernetes/api/client/listers/compose/v1beta2.NewStackLister instead
14:// Deprecated: Use github.com/docker/compose-on-kubernetes/api/client/listers/compose/v1beta2.StackNamespaceLister instead

kubernetes/client/informers/internalinterfaces/factory_interfaces.go
3:import api "github.com/docker/compose-on-kubernetes/api/client/informers/internalinterfaces"
6:// Deprecated: Use github.com/docker/compose-on-kubernetes/api/client/informers/internalinterfaces.NewInformerFunc instead
10:// Deprecated: Use github.com/docker/compose-on-kubernetes/api/client/informers/internalinterfaces.SharedInformerFactory instead

kubernetes/client/listers/compose/v1beta2/expansion_generated.go
3:import api "github.com/docker/compose-on-kubernetes/api/client/listers/compose/v1beta2"
7:// Deprecated: Use github.com/docker/compose-on-kubernetes/api/client/listers/compose/v1beta2.StackListerExpansion instead
12:// Deprecated: Use github.com/docker/compose-on-kubernetes/api/client/listers/compose/v1beta2.StackNamespaceListerExpansion instead

kubernetes/compose/v1beta1/register.go
3:import api "github.com/docker/compose-on-kubernetes/api/compose/v1beta1"
6:// Deprecated: Use github.com/docker/compose-on-kubernetes/api/compose/v1beta1.GroupName instead
12:     // Deprecated: Use github.com/docker/compose-on-kubernetes/api/compose/v1beta1.SchemeGroupVersion instead
14:     // Deprecated: Use github.com/docker/compose-on-kubernetes/api/compose/v1beta1.SchemeBuilder instead
16:     // Deprecated: Use github.com/docker/compose-on-kubernetes/api/compose/v1beta1.AddToScheme instead
21:// Deprecated: Use github.com/docker/compose-on-kubernetes/api/compose/v1beta1.Resource instead

kubernetes/client/clientset/clientset.go
3:import api "github.com/docker/compose-on-kubernetes/api/client/clientset"
6:// Deprecated: Use github.com/docker/compose-on-kubernetes/api/client/clientset.Interface instead
11:// Deprecated: Use github.com/docker/compose-on-kubernetes/api/client/clientset.Clientset instead
15:// Deprecated: Use github.com/docker/compose-on-kubernetes/api/client/clientset.NewForConfig instead
20:// Deprecated: Use github.com/docker/compose-on-kubernetes/api/client/clientset.NewForConfigOrDie instead
24:// Deprecated: Use github.com/docker/compose-on-kubernetes/api/client/clientset.New instead

kubernetes/compose/v1beta1/stack.go
3:import api "github.com/docker/compose-on-kubernetes/api/compose/v1beta1"
6:// Deprecated: Use github.com/docker/compose-on-kubernetes/api/compose/v1beta1.StackList instead
10:// Deprecated: Use github.com/docker/compose-on-kubernetes/api/compose/v1beta1.Stack instead
14:// Deprecated: Use github.com/docker/compose-on-kubernetes/api/compose/v1beta1.StackSpec instead
18:// Deprecated: Use github.com/docker/compose-on-kubernetes/api/compose/v1beta1.StackPhase instead
24:     // Deprecated: Use github.com/docker/compose-on-kubernetes/api/compose/v1beta1.StackAvailable instead
27:     // Deprecated: Use github.com/docker/compose-on-kubernetes/api/compose/v1beta1.StackProgressing instead
31:     // Deprecated: Use github.com/docker/compose-on-kubernetes/api/compose/v1beta1.StackFailure instead
36:// Deprecated: Use github.com/docker/compose-on-kubernetes/api/compose/v1beta1.StackStatus instead

kubernetes/client/informers/generic.go
3:import api "github.com/docker/compose-on-kubernetes/api/client/informers"
7:// Deprecated: Use github.com/docker/compose-on-kubernetes/api/client/informers.GenericInformer instead

kubernetes/compose/v1beta1/parsing.go
3:import api "github.com/docker/compose-on-kubernetes/api/compose/v1beta1"
6:// Deprecated: Use github.com/docker/compose-on-kubernetes/api/compose/v1beta1.MaxComposeVersion instead

kubernetes/compose/v1beta2/scale.go
3:import api "github.com/docker/compose-on-kubernetes/api/compose/v1beta2"
6:// Deprecated: Use github.com/docker/compose-on-kubernetes/api/compose/v1beta2.Scale instead

kubernetes/client/clientset/typed/compose/v1beta1/compose_client.go
3:import api "github.com/docker/compose-on-kubernetes/api/client/clientset/typed/compose/v1beta1"
6:// Deprecated: Use github.com/docker/compose-on-kubernetes/api/client/clientset/typed/compose/v1beta1.ComposeV1beta1Interface instead
10:// Deprecated: Use github.com/docker/compose-on-kubernetes/api/client/clientset/typed/compose/v1beta1.ComposeV1beta1Client instead
14:// Deprecated: Use github.com/docker/compose-on-kubernetes/api/client/clientset/typed/compose/v1beta1.NewForConfig instead
19:// Deprecated: Use github.com/docker/compose-on-kubernetes/api/client/clientset/typed/compose/v1beta1.NewForConfigOrDie instead
23:// Deprecated: Use github.com/docker/compose-on-kubernetes/api/client/clientset/typed/compose/v1beta1.New instead

kubernetes/compose/v1beta2/owner.go
3:import api "github.com/docker/compose-on-kubernetes/api/compose/v1beta2"
6:// Deprecated: Use github.com/docker/compose-on-kubernetes/api/compose/v1beta2.Owner instead

kubernetes/client/informers/compose/interface.go
3:import api "github.com/docker/compose-on-kubernetes/api/client/informers/compose"
6:// Deprecated: Use github.com/docker/compose-on-kubernetes/api/client/informers/compose.Interface instead
10:// Deprecated: Use github.com/docker/compose-on-kubernetes/api/client/informers/compose.New instead

kubernetes/client/clientset/scheme/register.go
3:import api "github.com/docker/compose-on-kubernetes/api/client/clientset/scheme"
7:      // Deprecated: Use github.com/docker/compose-on-kubernetes/api/client/clientset/scheme.Scheme instead
9:      // Deprecated: Use github.com/docker/compose-on-kubernetes/api/client/clientset/scheme.Codecs instead
11:     // Deprecated: Use github.com/docker/compose-on-kubernetes/api/client/clientset/scheme.ParameterCodec instead
29:// Deprecated: Use github.com/docker/compose-on-kubernetes/api/client/clientset/scheme.AddToScheme instead

kubernetes/compose/v1beta2/composefile_stack_types.go
3:import api "github.com/docker/compose-on-kubernetes/api/compose/v1beta2"
6:// Deprecated: Use github.com/docker/compose-on-kubernetes/api/compose/v1beta2.ComposeFile instead

kubernetes/client/informers/compose/v1beta2/stack.go
3:import api "github.com/docker/compose-on-kubernetes/api/client/informers/compose/v1beta2"
7:// Deprecated: Use github.com/docker/compose-on-kubernetes/api/client/informers/compos [...]

2021-08-03 16:51 UTC, cpuguy83 commented
<img width="192" alt="image" src="https://user-images.githubusercontent.com/799078/128054973-d7a13c55-7e0e-4732-be61-31ac1320f862.png">

💯

2022-02-22 10:13 UTC, thaJeztah requested changes
Thanks! Left one comment in-line w.r.t. the test, and some comment about (probably ok as follow-up)

Could you;

- have a quick peek at the test (do we still need that case? if so, should it be in a separate test? or should we remove it?)
- squash the commits; I think the first commit doesn't build (so would disallow doing a `git bisect`); it's probably fine to squash all commits to a single one
- Looks like a linter isn't happy;

```
cli/command/context/create.go:6: File is not `goimports`-ed (goimports)
    "github.com/sirupsen/logrus"
cli/command/context/update.go:6: File is not `goimports`-ed (goimports)
    "github.com/sirupsen/logrus"
```

2022-02-22 10:13 UTC, thaJeztah commented on cli/command/context/create.go
> +		logrus.Warn("kubernetes orchestrator is deprecated")
I wanted to suggest to perhaps just use `fmt.Printf()` here (as logrus formatting is a bit "meh" on the CLI), but I'm ok with doing in a follow-up; 

```bash
docker context create --docker host=tcp://localhost:2375 --kubernetes host=http://foo:1234 bla
WARN[0000] kubernetes orchestrator is deprecated
bla
Successfully created context "bla"
```

Perhaps we should generate the warning earlier, or use `flags.MarkDeprecated()` (which both hides the flag, and prints a deprecation message)

Giving it a quick try what it looks like with `flags.MarkDeprecated()`;

<details>

```patch
diff --git a/cli/command/context/update.go b/cli/command/context/update.go
index 55f775037..bcf1a6101 100644
--- a/cli/command/context/update.go
+++ b/cli/command/context/update.go
@@ -3,7 +3,6 @@ package context
 import (
        "bytes"
        "fmt"
-       "github.com/sirupsen/logrus"
        "text/tabwriter"

        "github.com/docker/cli/cli"
@@ -60,8 +59,8 @@ func newUpdateCommand(dockerCli command.Cli) *cobra.Command {
        flags.SetAnnotation("default-stack-orchestrator", "deprecated", nil)
        flags.StringToStringVar(&opts.Docker, "docker", nil, "set the docker endpoint")
        flags.StringToStringVar(&opts.Kubernetes, "kubernetes", nil, "set the kubernetes endpoint")
+       flags.MarkDeprecated("kubernetes", "option will be ignored")
        flags.SetAnnotation("kubernetes", "kubernetes", nil)
-       flags.SetAnnotation("kubernetes", "deprecated", nil)
        return cmd
 }

@@ -102,9 +101,6 @@ func RunUpdate(cli command.Cli, o *UpdateOptions) error {
                c.Endpoints[docker.DockerEndpoint] = dockerEP
                tlsDataToReset[docker.DockerEndpoint] = dockerTLS
        }
-       if len(o.Kubernetes) != 0 {
-               logrus.Warn("kubernetes orchestrator is deprecated")
-       }
        if err := validateEndpointsAndOrchestrator(c); err != nil {
                return err
        }
```

</details>


```bash
docker context update --kubernetes host=tcp://foo:1234 bla
Flag --kubernetes has been deprecated, option will be ignored
bla
Successfully updated context "bla"
```

2022-02-22 10:13 UTC, thaJeztah commented
I also had a quick look at what it looks like on this PR; I think there's some follow-up changes we should make

First of all, wondering if we should consider removing the `ORCHESTRATOR` column from the default output (although we could probably do this in a follow-up);

```bash
docker context ls
NAME        DESCRIPTION                               DOCKER ENDPOINT               ORCHESTRATOR
default *   Current DOCKER_HOST based configuration   unix:///var/run/docker.sock   swarm
```

Looking at `docker context create`, there's some bits we should change;

```bash
docker context create --help

Usage:  docker context create [OPTIONS] CONTEXT

Create a context

Docker endpoint config:

NAME                DESCRIPTION
from                Copy named context's Docker endpoint configuration
host                Docker endpoint on which to connect
ca                  Trust certs signed only by this CA
cert                Path to TLS certificate file
key                 Path to TLS key file
skip-tls-verify     Skip TLS certificate validation

Example:

$ docker context create my-context --description "some description" --docker "host=tcp://myserver:2376,ca=~/ca-file,cert=~/cert-file,key=~/key-file"

Options:
      --default-stack-orchestrator string   Default orchestrator for stack operations to use with this context (swarm|kubernetes|all)
      --description string                  Description of the context
      --docker stringToString               set the docker endpoint (default [])
      --from string                         create context from a named context
      --kubernetes stringToString           set the kubernetes endpoint (default [])
```

From the above, I would suggest to:

- the `--default-stack-orchestrator` still mentions `kubernetes` (as well as `all`); 
- hide the `--kubernetes` flag; we can keep it as hidden (so that the warning (or error) can be printed)
- same for `--default-stack-orchestrator`

It looks like there's logic in various locations to (e.g.) normalize Orchestrator, etc. etc. that we should probably remove. Effectively we'll only have 1 orchestrator now (swarmkit; and only if swarmkit is enabled), so perhaps there's more cruft to remove.

2022-02-22 15:02 UTC, ndeloof commented
@thaJeztah squashed and removed support for multiple orchestrator in context store / stack commands

2022-02-23 13:19 UTC, thaJeztah approved these changes
LGTM, thanks for updating.

I was going through the code, and noticed there's a bunch of locations still referring to the removed options (docs, completion scripts), but let me open a follow-up PR for those changes (possibly there's more, so let's first remove what we have in this PR).

2022-02-23 13:52 UTC, thaJeztah commented
@silvin-lubecki this one good to go?

2022-02-24 09:17 UTC, silvin-lubecki approved these changes
LGTM, but @thaJeztah should we update https://github.com/docker/cli/blob/master/docs/deprecated.md#kubernetes-stack-and-context-support and marked it as removed ?

2022-02-24 09:30 UTC, thaJeztah commented
> should we update https://github.com/docker/cli/blob/master/docs/deprecated.md#kubernetes-stack-and-context-support and marked it as removed ?

Yes! I had some changes already locally as follow-up (didn't want to block the PR 😅), but I see @ndeloof updated it (thanks!); let's merge this when CI completes 👍

2022-02-24 09:32 UTC, thaJeztah commented
LOL, and of course some failure in CI now (looks like it may be a flaky / race (based on the name of the test);

```
--- FAIL: TestInitTtySizeErrors (0.13s)
[33](https://github.com/docker/cli/runs/5316603375?check_suite_focus=true#step:5:33)
    tty_test.go:29: assertion failed: 
[34](https://github.com/docker/cli/runs/5316603375?check_suite_focus=true#step:5:34)
        --- expectedError
[35](https://github.com/docker/cli/runs/5316603375?check_suite_focus=true#step:5:35)
        +++ →
[36](https://github.com/docker/cli/runs/5316603375?check_suite_focus=true#step:5:36)
        @@ -1,2 +1 @@
[37](https://github.com/docker/cli/runs/5316603375?check_suite_focus=true#step:5:37)
        -failed to resize tty, using default size
```

I'll kick CI again

2022-02-24 09:38 UTC, thaJeztah commented
It's green! ✅✅ ✅ ✅

2022-02-24 09:38 UTC, merged