Describe privileged mode in terms of capibilities
docker/cli pull request #3419
Opened 2022-02-06 14:56 UTC by iainelder

I didn't see where in the page that `--privileged` mode adds all capabilities.

I think this page once did contain that information. I got it from a Stack Overflow answer that seems to have copied from an earlier version of this same document.
 
> Full container capabilities (--privileged)
>
> The --privileged flag gives all capabilities to the container, and it also lifts all the limitations enforced by the device cgroup controller. In other words, the container can then do almost everything that the host can do. This flag exists to allow special use-cases, like running Docker within Docker.

https://stackoverflow.com/a/36441605/111424

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

2022-02-07 11:12 UTC, thaJeztah requested changes
Thanks for contributing!

Your changes look good to me (but I may have a look at doing a follow-up to look at the bits I mentioned above).

However, It appears your commit message is missing a DCO sign-off,
causing the DCO check to fail.

We require all commit messages to have a `Signed-off-by` line with your name
and e-mail (see ["Sign your work"](https://github.com/moby/moby/blob/v20.10.11/CONTRIBUTING.md#sign-your-work)
in the CONTRIBUTING.md in this repository), which looks something like:

```
Signed-off-by: YourFirsName YourLastName <yourname@example.org>
```

There is no need to open a new pull request, but to fix this (and make CI pass),
you need to _amend_ the commit(s) in this pull request, and "force push" the amended
commit.

Unfortunately, it's not possible to do so through GitHub's web UI, so this needs
to be done through the git commandline.

You can find some instructions in the output of the DCO check (which can be found
in the "checks" tab on this pull request), as well as in the [Moby contributing guide](https://github.com/moby/moby/blob/v20.10.11/docs/contributing/set-up-git.md).

Steps to do so "roughly" come down to:

1. Set your name and e-mail in git's configuration:

    ```bash
    git config --global user.name "YourFirstName YourLastName"
    git config --global user.email "yourname@example.org"
    ```

    (Make sure to use your _real_ name (**not your GitHub username/handle**) and e-mail)


2. Clone your fork locally
3. Check out the branch associated with this pull request
4. Sign-off and amend the existing commit(s)

    ```bash
    git commit --amend --no-edit --signoff
    ```

    If your pull request contains multiple commits, either squash the commits (if
    needed) or sign-off each individual commit.

5. _Force push_ your branch to GitHub (using the `--force` or [`--force-with-lease`](https://stackoverflow.com/questions/52823692/git-push-force-with-lease-vs-force) flags) to update the pull request.


Sorry for the hassle (I wish GitHub would make this a bit easier to do), and let me know if you need help or more detailed instructions!

2022-02-07 11:21 UTC, iainelder commented
@thaJeztah thanks for such a detailed and thoughtful reply! Sorry about the signing issues. I just made the change quickly through the Github console. I'll review your comments more carefully later today.

2022-02-08 13:59 UTC, iainelder commented
I followed your guide and corrected a typo along the way. Thanks for being patient with a first-time contributor!

2022-02-08 19:08 UTC, iainelder commented
> Looks like that quote comes from the reference page for the docker run subcommand

Thanks for spotting the source! I've updated the Stack Overflow answer with a link to the quoted page.

> a container that's created with --privileged _does not contain_

A canonical section about privileged mode ought to open with that phrase. In a big red warning box :grinning: 

Your summary now is the most complete and succinct description of privileged mode I know. I'd love to see it in the main documentation.

Often while researching how to give my container just enough permissions to do what I need, I see people solving the error I have with a quick `--privileged` switch, without explaining or perhaps understanding the implications.

2022-02-14 18:31 UTC, iainelder commented
@thaJeztah are there any more changes you need me to make?

The DCO test appears to have passed.

2022-04-01 20:34 UTC, thaJeztah commented
Sorry for the long delay 😬 I think I miss-clicked on my mobile phone and muted notifications for this one

looks like CI needs a kick because some changes were made to GitHub actions in the master branch; let me close and reopen to trigger it and refresh the actions config

2022-04-01 20:35 UTC, thaJeztah approved these changes
changes LGTM, thanks!!

2022-04-01 22:13 UTC, merged

2022-04-01 23:30 UTC, iainelder commented
Thanks for merging it :-)