Add --force option to network rm subcommand
docker/cli pull request #3547
Opened 2022-04-09 03:16 UTC by cavcrosby

**- What I did**

Added a `-f` / `--force` option to the network's `rm` subcommand. What this option allows is for a user to remove a configured Docker network but return a zero status code even if said network does not exist (stdout will also still display the network name). Similar to Unix's `rm --force` command. This closes #2382.

**- How I did it**

I was inspired by the volume `rm` subcommand's `--force` option (at least on the client-side) so hence my implementation is similar to it. However, like #2678, my changes only affect the client and are currently not implemented for the daemon. 

**- How to verify it**

`docker network rm --force foo`

**- Description for the changelog**

Add --force option to network rm subcommand.

**- A picture of a cute animal (not mandatory but encouraged)**

![image](https://user-images.githubusercontent.com/31086993/162554319-c53b50ea-7378-43a3-b308-3227ef533f7d.png)

2022-04-09 16:13 UTC, cavcrosby commented
That's no bueno (or good), err, can I get a maintainer's thoughts?

2022-04-14 14:31 UTC, thaJeztah requested changes
Thanks for working on this!

I left some suggestions inline, but was writing some of the changes while reviewing, so I'll open a pull request against your branch with those

2022-04-14 14:33 UTC, thaJeztah commented
I opened https://github.com/cavcrosby/docker-cli/pull/1 (which, once merged, should appear in this PR); perhaps you can also squash the commits (no need to preserve my commit as a separate commit); happy to help doing so if you want!

2022-04-16 02:26 UTC, cavcrosby commented on cli/command/network/remove.go
> +	flags.SetAnnotation("force", "version", []string{"1.25"})
Yup, was a copypasta from the `docker volume rm`.

2022-04-22 01:59 UTC, cavcrosby commented
Squashed your commit, and closed out the PR on my fork. Should be good to go but let me know what you think.

2022-04-25 09:43 UTC, albers approved these changes
Completion LGTM, thanks.

2022-04-29 11:57 UTC, thaJeztah reviewed
changes LGTM, thanks!

I think we can combine the 5 commits into one, as they're all related (and some of the later ones touch up previous ones); let me do a quick squash and push to the PR branch

2022-04-29 11:58 UTC, thaJeztah approved these changes

2022-04-30 09:56 UTC, thaJeztah commented
All green; let's get this one in

Thanks!

2022-04-30 09:56 UTC, merged