Add note about dual logging with `docker logs`
docker/cli pull request #3855
Opened 2022-11-08 15:24 UTC by matletix

Specify that `docker logs` works with all logging drivers if dual logging is enabled

Signed-off-by: Mathieu Rollet <matletix@gmail.com>

- What I did

Since Docker Engine 20.10, dual logging allows `docker logs` to work regardless of the logging driver used. This is not specified in the note mentioning the limitations of `docker logs`.

- How I did it

Add a link to the dual logging documentation in the aforementioned note.

- How to verify it

Check the diff

- Description for the changelog

Minor update to the CLI docker logs documentation

2022-11-17 12:51 UTC, thaJeztah requested changes
Thanks for contributing! I left a suggestion; let me know what you think.

2022-11-17 12:51 UTC, thaJeztah commented on docs/reference/commandline/logs.md
> +> [dual logging](https://docs.docker.com/config/containers/logging/dual-logging/) is enabled.
Given that dual logging is now automatically used if needed, perhaps the better options would be to remove this note as a whole (effectively it now "just works", so removing the block reduces noise)

2022-11-18 09:00 UTC, matletix commented
Right, I removed the note

2022-11-18 14:04 UTC, thaJeztah approved these changes
LGTM, thanks!

2022-11-18 14:04 UTC, merged