Replace uses of `strings.Split(N)` with `strings.Cut()`
docker/cli pull request #3936
Opened 2022-12-27 16:48 UTC by thaJeztah

Similar to https://github.com/moby/moby/pull/44381

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

2022-12-28 07:05 UTC, thaJeztah commented
@rumpl ptal 🤗

2022-12-29 13:21 UTC, vvoland requested changes
Small typo 😅

2022-12-29 14:12 UTC, thaJeztah commented on cli/command/container/opts.go
> +		if !ok && k != "no-new-privileged" {
Oh! 💩 🙈 Good catch. I, erm, blame auto-correct, but I likely fat-fingered 😂 .

2022-12-29 15:22 UTC, thaJeztah commented
@vvoland fixed the typos 😅 


(I'd love to get rid of some of that logic in the ParseSecurityOpts; I don't think it should all belong in that function, or even in the CLI code)

2022-12-29 15:23 UTC, vvoland approved these changes
LGTM

2022-12-29 18:02 UTC, merged