Docs freshness updates to Docker run command docs
docker/cli pull request #4144
Opened 2023-03-31 09:58 UTC by ChrisChinchilla

This ended up being a lot more changes than expected, but is something of a refresh for consistency, style, understanding, and freshness.

2023-03-31 10:02 UTC, thaJeztah commented
Thank you for contributing! It appears your commit message is missing a DCO sign-off,
causing the DCO check to fail.

We require all commit messages to have a `Signed-off-by` line with your name
and e-mail (see ["Sign your work"](https://github.com/moby/moby/blob/v20.10.11/CONTRIBUTING.md#sign-your-work)
in the CONTRIBUTING.md in this repository), which looks something like:

```
Signed-off-by: YourFirsName YourLastName <yourname@example.org>
```

There is no need to open a new pull request, but to fix this (and make CI pass),
you need to _amend_ the commit(s) in this pull request, and "force push" the amended
commit.

Unfortunately, it's not possible to do so through GitHub's web UI, so this needs
to be done through the git commandline.

You can find some instructions in the output of the DCO check (which can be found
in the "checks" tab on this pull request), as well as in the [Moby contributing guide](https://github.com/moby/moby/blob/v20.10.11/docs/contributing/set-up-git.md).

Steps to do so "roughly" come down to:

1. Set your name and e-mail in git's configuration:

    ```bash
    git config --global user.name "YourFirstName YourLastName"
    git config --global user.email "yourname@example.org"
    ```

    (Make sure to use your _real_ name (**not your GitHub username/handle**) and e-mail)


2. Clone your fork locally
3. Check out the branch associated with this pull request
4. Sign-off and amend the existing commit(s)

    ```bash
    git commit --amend --no-edit --signoff
    ```

    If your pull request contains multiple commits, either squash the commits (if
    needed) or sign-off each individual commit.

5. _Force push_ your branch to GitHub (using the `--force` or [`--force-with-lease`](https://stackoverflow.com/questions/52823692/git-push-force-with-lease-vs-force) flags) to update the pull request.


Sorry for the hassle (I wish GitHub would make this a bit easier to do), and let me know if you need help or more detailed instructions!

2023-04-07 22:28 UTC, thaJeztah requested changes
Thanks! Quite some improvements in here. While reading, I found some issues, and left some comments (some aren't new, but might be something we need to look into, which can be in a follow up)

Let me know if you want to go through some of them!

2023-04-07 22:30 UTC, thaJeztah commented
Ugh! Looks like GitHub is a bit over-enthusiastic again, and hid some of my comments, so you may have to expand those ⚠️ 

![IMG_7686](https://user-images.githubusercontent.com/1804568/230686705-60c004a5-505b-4fe6-ae74-4fe7acaee6fa.jpeg)

2023-04-11 11:44 UTC, ChrisChinchilla commented on docs/reference/commandline/run.md
> +The `-w` flag runs the command executed inside the directory specified, in this example,
```suggestion
The `-w` option runs the command executed inside the directory specified, in this example,
```

2023-04-11 11:47 UTC, ChrisChinchilla commented on docs/reference/commandline/run.md
> +`-p 127.0.0.1:80:80`) is externally accessible. This also applies if
```suggestion
`-p 127.0.0.1:80:80`) are externally accessible. This also applies if
```

2023-04-11 11:48 UTC, ChrisChinchilla commented on docs/reference/commandline/run.md
> +containers. You can specify containers by repetitions of the `--volumes-from`
```suggestion
containers. You can specify more than one container by repetitions of the `--volumes-from`
```

How about the above @thaJeztah ?

2023-04-11 11:50 UTC, ChrisChinchilla commented on docs/reference/commandline/run.md
> +This isn't going to print anything to console unless there's an error because output
```suggestion
This isn't going to print anything to the console unless there's an error because output
```

Both work, but I'm not fussed

2023-04-11 11:52 UTC, ChrisChinchilla commented on docs/reference/commandline/run.md
> +This example shows a way of using `--attach` to pipe a build file into a container.
```suggestion
This example shows a way of using `--attach` to pipe a file into a container.
```

2023-04-11 11:55 UTC, thaJeztah commented on docs/reference/commandline/run.md
> +containers. You can specify containers by repetitions of the `--volumes-from`
Works for me!

2023-04-11 12:08 UTC, ChrisChinchilla commented on docs/reference/commandline/run.md
> +To start a container and connect it to a network, use the `--network` flag.
```suggestion
To start a container and connect it to a network, use the `--network` option to connect the container to a network.
```

2023-04-17 11:14 UTC, ChrisChinchilla commented on docs/reference/commandline/run.md
> +`/containers/(id)/start`. You can restart a stopped container with all its
@thaJeztah I'm a bit confused by this comment. Are you saying replace the entire paragraph with the suggestion in the comment?

or, make the opening paragraph more general and then maybe paragraph "two" is the suggestion?

2023-04-17 13:04 UTC, ChrisChinchilla commented on docs/reference/commandline/run.md
>  a container writes files. The `--read-only` flag mounts the container's root
Ok, added to sub-section for now and noted for more details.

2023-04-26 10:38 UTC, thaJeztah approved these changes
changes LGTM; could you squash the commits?

2023-04-26 11:09 UTC, ChrisChinchilla commented
@thaJeztah Done!

2023-04-26 13:34 UTC, thaJeztah approved these changes
LGTM, thanks!

2023-04-26 14:20 UTC, thaJeztah commented
All green now 👍

2023-04-26 14:20 UTC, merged