Output valid json for docker ps --format='{{json .}}'
docker/cli pull request #4705
Opened 2023-12-09 09:37 UTC by bdpiprava

Attempt to fix https://github.com/moby/moby/issues/46906

**- What I did**
Extended [formatter.go](https://github.com/docker/cli/blob/master/cli/command/formatter/formatter.go) to output valid json array

**- How I did it**
Modified built-in functions in the [formatter.go](https://github.com/docker/cli/blob/master/cli/command/formatter/formatter.go)  to add required prefix and suffix to generate valid json array.

**- How to verify it**
1. Must have multiple docker containers in any state
2. Run `docker ps -a --format='{{json .}}'`

**- Description for the changelog**
- Output valid json for `docker ps --format={{json .}}`

2023-12-12 10:34 UTC, bdpiprava commented
@thaJeztah  - May I request some help on the PR?

2023-12-16 17:15 UTC, AkihiroSuda requested changes
For compatibility reason, I suggest closing this.

The docs might need an update to explain the current behavior.

2023-12-18 06:08 UTC, bdpiprava commented
@AkihiroSuda - I understand that this change may cause the compatibility to break but from the use-case point of view when we say `docker ps --format json` the expected output should be a valid json array as `docker ps` is to list the containers. WDYT?

P.S. May I ask if you can elaborate more on `compatibility reason` ?

2023-12-18 06:31 UTC, AkihiroSuda commented
> @AkihiroSuda - I understand that this change may cause the compatibility to break but from the use-case point of view when we say `docker ps --format json` the expected output should be a valid json array as `docker ps` is to list the containers. WDYT?

Users have been depending on the current behavior, so it can't be fixed, regardless to its validity

> P.S. May I ask if you can elaborate more on `compatibility reason` ?

Changing the behavior will break existing users' scripts, so it is unlikely acceptable

2023-12-18 06:48 UTC, bdpiprava commented
As explained by @AkihiroSuda, I am closing the MR.

2023-12-18 06:48 UTC, closed without merging