#770 - Removed all mentions of "please" from docs and messages
docker/cli pull request #5040
Opened 2024-04-26 18:29 UTC by ggracechoi

**- What I did**
We removed all references to the word "please" throughout the entire repository. 

**- How I did it**
We used the search feature to look for all mentions of "please" and removed them. We also capitalized the following word if the "please" was the first word in the sentence.

**- How to verify it**
Use the search feature to look for instances of "please" in the code base.

**- Description for the changelog**

```markdown changelog
All mentions of the word "please" were removed from the docs and messages in this repository.

```

**- A picture of a cute animal (not mandatory but encouraged)**
![tiger](https://github.com/docker/cli/assets/52022191/3001d771-8c6c-47d7-b15c-14d9da3e5b00)

**- Note**
We didn't realize we had to sign off on our commit, so we're including it in this PR since it's too late to include it in the commit message. 
Signed-off-by: Grace Choi <grace.54109@gmail.com>
Signed-off-by: Pranjal Rai <pranjalrai@utexas.edu>

2024-05-14 14:55 UTC, vvoland commented
What's wrong with having "please"?

2024-05-15 17:10 UTC, thaJeztah commented
@vvoland I think this PR is to address;

- https://github.com/docker/cli/issues/770


There's various articles on this, but here's a nice one that outlines some reasoning; https://medium.com/@xupeilan05/why-please-has-no-place-in-ux-writing-tips-for-clear-and-assertive-copy-bd096b7f976a

2024-05-15 17:15 UTC, thaJeztah commented
OH! I think the DCO may be the DCO check being too restrictive; 

> Commit sha: [a0df7b9](https://github.com/docker/cli/pull/5040/commits/a0df7b9a04fb86fb60adcaf2ae9fae748e8f2524), Author: Grace Choi, Committer: Grace Choi; Can not find "Grace Choi [grace.54109@gmail.com](mailto:grace.54109@gmail.com)", in ["Grace Choi [gracechoi@utexas.edu](mailto:gracechoi@utexas.edu)", "Pranjal Rai [pranjalrai@utexas.edu](mailto:pranjalrai@utexas.edu)"].


It's probably fine to mark that as "ok" manually; let me do so.

2024-05-15 17:20 UTC, thaJeztah requested changes
looks like this PR is modifying the `vendor/` directory (see my comment)

2024-05-15 17:20 UTC, thaJeztah commented on vendor/github.com/Microsoft/go-winio/README.md
> +See the LICENSE file for licensing information.
Oh! Files inside the `vendor/` directory are dependencies we use, but those are not maintained by us, and none of the files inside the `vendor/` directory should be edited by us.

Can you revert changes inside `vendor/` ?

2024-06-11 14:48 UTC, thaJeztah commented
- carrying in https://github.com/docker/cli/pull/5141

2024-06-11 20:01 UTC, closed without merging